# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          fetch-depth: 0 # fetch all history for all branches and tags
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest # Using --cov=. --cov-report=xml to create a coverage and export it as an xml file
        run: |
          pytest --cov=. --cov-report=xml
      - name: SonarCloud Scan # Add a SonarCloud Scan step to make the connection with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to registry
        run: echo ${{ secrets.PERSONAL_TOKEN }} | docker login ghcr.io -u TitusVM --password-stdin
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/titusvm/indu_log_tp2:latest
      - name: Push the image into the registry
        run: docker push ghcr.io/titusvm/indu_log_tp2:latest
